-- Add SKD-SKB integration score fields to exam_sessions table
ALTER TABLE "exam_sessions"
  ADD COLUMN IF NOT EXISTS "maks_skd" INTEGER NOT NULL DEFAULT 550,
  ADD COLUMN IF NOT EXISTS "maks_skb" INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS "skor_skb" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "nilai_integrasi_skd" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "nilai_integrasi_skb" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "total_nilai_akhir" DOUBLE PRECISION NOT NULL DEFAULT 0;